name: Workflow

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install DVC and Google Drive dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gs]

      - name: Install dependencies and run DVC pipeline
        run: |
          pip install -r requirements.txt
          dvc repro
